### ISSUE TITLE
Publish Home Assistant auto-discovery sensors

### ISSUE THREAD

**Issue by That-Dude** [nygma2004/growatt2mqtt#7]
First of all I just want to say thank you for this project. I've got it working with my Growatt inverter and learned so much in the process.

I use Home Assistant and the trickiest part was figuring out how to import the values, I achieved this by adding MQTT sensors to my `configuration.yaml` but it's a hacky solution.

```
sensor:
- platform: mqtt
  name: 'Growatt Solarpower'
  state_topic: 'growatt/data'
  value_template: '{{ value_json.solarpower }}'
  unit_of_measurement: 'W'
  device_class: power

- platform: mqtt
  name: 'Growatt Enery Today'
  state_topic: 'growatt/data'
  value_template: '{{ value_json.energytoday }}'
  unit_of_measurement: 'kWh'
  device_class: energy
```

I was wondering if you might add the functionality to publish the sensors from your sketch into the `homeassistant/sensor/growatt' topic, as this would allow Home Assistant auto-discovery:

I borrowed this example from another solution: 

```
Topic :homeassistant/sensor/inverter_1_pv_power/config

{"device":{"ids":["sa_inverter"],"mdl":"Growatt MIN/MIC","mf":"Growatt","name":"Growatt MIN/MIC"},"device_class":"power","name":"PV power","state_topic":"solar/inverter_1/pv_power/state","uniq_id":"inverter_1_pv_power","unit_of_measurement":"W"}
```
